global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'apps'
    scheme: https
    metrics_path: /metrics
    tls_config:
      cert_file: /etc/prometheus/certs/balancer.crt
      key_file: /etc/prometheus/certs/balancer.key
      ca_file: /etc/prometheus/certs/ca.crt
      insecure_skip_verify: true
    static_configs:
      - targets: ['app1:8443', 'app2:8443']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
